/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.emailsend;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.AddressException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author luish
 */
public class servidor extends javax.swing.JDialog {

    String servidorSmtp2;
    int puerto2;
    boolean tls2;
    String usuario2;
    String clave2;
    String remitente2;
    String destinatario2;
    String asunto2;
    String cuerpo2;
    String rutaFichero;
    
    EmailSend emailSend;

    public void establecerPropiedades() {
       servidorSmtp2 = this.servidorSmtp.getText();
        puerto2 = (int) this.puerto.getValue();
        tls2 = this.noTls.isSelected() ? false : true;
        usuario2 = this.usuario.getText();
        clave2 = this.clave.getText();
        remitente2 = this.remitente.getText();
        destinatario2 = this.destinatario.getText();
        asunto2 = this.asunto.getText();
        cuerpo2 = this.cuerpoMensaje.getText();
    }

    boolean conectado = false;

    /**
     * Creates new form servidor
     */
    public servidor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        enviarMensaje.setEnabled(false);
        cuerpoMensaje.setEnabled(false);
        asunto.setEnabled(false);
        botonAdjuntar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        servidorSmtp = new javax.swing.JTextField();
        noTls = new javax.swing.JRadioButton();
        siTls = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clave = new javax.swing.JTextField();
        botonConectar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        asunto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        destinatario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        remitente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuerpoMensaje = new javax.swing.JTextArea();
        enviarMensaje = new javax.swing.JButton();
        puerto = new javax.swing.JSpinner();
        botonAdjuntar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        servidorSmtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servidorSmtpActionPerformed(evt);
            }
        });

        buttonGroup1.add(noTls);
        noTls.setSelected(true);
        noTls.setText("Sin TLS ");

        buttonGroup1.add(siTls);
        siTls.setText("Con TLS");

        jLabel1.setText("Servidor SMTP");

        jLabel2.setText("Puerto");

        jLabel3.setText("Usuario");

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Clave");

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        botonConectar.setText("Conectar");
        botonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarActionPerformed(evt);
            }
        });

        jLabel5.setText("Remitente");

        asunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuntoActionPerformed(evt);
            }
        });

        jLabel6.setText("Destinatario");

        destinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinatarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Asunto");

        remitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remitenteActionPerformed(evt);
            }
        });

        jLabel8.setText("Redacta el cuerpo del mensaje:");

        cuerpoMensaje.setColumns(20);
        cuerpoMensaje.setRows(5);
        jScrollPane1.setViewportView(cuerpoMensaje);

        enviarMensaje.setText("Enviar mensaje");
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        botonAdjuntar.setText("📎");
        botonAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdjuntarActionPerformed(evt);
            }
        });

        jLabel9.setText("Adjuntar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(28, 28, 28)
                                        .addComponent(servidorSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(noTls)
                                        .addGap(18, 18, 18)
                                        .addComponent(siTls))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(enviarMensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAdjuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(remitente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servidorSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTls)
                    .addComponent(siTls)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonConectar)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(botonAdjuntar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enviarMensaje)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servidorSmtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servidorSmtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servidorSmtpActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    private void asuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuntoActionPerformed

    private void destinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinatarioActionPerformed

    private void remitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remitenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remitenteActionPerformed

    private void botonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarActionPerformed

    establecerPropiedades();
        
        if (conectado == false) {
    String tlsT = (tls2 ? "true" : "false");
    emailSend = new EmailSend(servidorSmtp2 ,usuario2, clave2, puerto2 + "", tlsT, destinatario2, cuerpo2, asunto2);
            if (!(servidorSmtp2.isEmpty() || puerto2 <= 0 && usuario2.isEmpty() || clave2.isEmpty() || remitente2.isEmpty() || destinatario2.isEmpty())) {
                try {
                    if (emailSend.conectar()) {
                        JOptionPane.showMessageDialog(this, "Conectado con exito bienvenido " + usuario2.split("@")[0]);
                        botonConectar.setText("Desconectar");
                        conectado = true;
                        enviarMensaje.setEnabled(true);
                        cuerpoMensaje.setEnabled(true);
                        botonAdjuntar.setEnabled(true);
                        asunto.setEnabled(true);
                    }
                } catch (MessagingException ex) {
                    Logger.getLogger(servidor.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "No se ha podido conectar");
                    borrarCampos();
                }

            }
            else{
                JOptionPane.showMessageDialog(this, "Completa todos los campos");
            }
        } else {
            conectado = false;
            botonConectar.setText("Conectar");
            enviarMensaje.setEnabled(false);
            cuerpoMensaje.setEnabled(false);
            botonAdjuntar.setEnabled(false);
            rutaFichero = null;
            asunto.setEnabled(false);
            emailSend = null;
            borrarCampos();
        }


    }//GEN-LAST:event_botonConectarActionPerformed

    
    private void borrarCampos(){
       servidorSmtp.setText("");
       this.puerto.setValue(0);
         this.usuario.setText("");
       this.clave.setText("");
       this.remitente.setText("");
       this.destinatario.setText("");
      this.asunto.setText("");
       this.cuerpoMensaje.setText("");
    
    }
    
    
    
    
    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        int opcion;
        establecerPropiedades();
        if (asunto2.isEmpty() || cuerpo2.isEmpty()) {
            opcion = JOptionPane.showConfirmDialog(this, "Estas seguro que quieres mandar un mensaje sin cuerpo");
        }
        else{
            opcion = JOptionPane.OK_OPTION;
        }
     
        
        
        String tlsT = (tls2 ? "true" : "false");
                try {
                    if (opcion == JOptionPane.OK_OPTION) {
                    emailSend.setAsunto(asunto2);
                    emailSend.setMensaje(cuerpo2);
                    emailSend.setRutaFichero(rutaFichero);
                    emailSend.mandarCorreo();
                  }

                } catch (MessagingException ex) {
                    Logger.getLogger(servidor.class.getName()).log(Level.SEVERE, null, ex);
                      Logger.getLogger(servidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(servidor.class.getName()).log(Level.SEVERE, null, ex);
        }
                if (opcion == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(this, "Mensaje enviado con exito");
                }
    }//GEN-LAST:event_enviarMensajeActionPerformed

    private void botonAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdjuntarActionPerformed

            JFileChooser fileChooser = new JFileChooser();
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                rutaFichero = selectedFile.getAbsolutePath();
            }

    }//GEN-LAST:event_botonAdjuntarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                servidor dialog = new servidor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asunto;
    private javax.swing.JButton botonAdjuntar;
    private javax.swing.JButton botonConectar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField clave;
    private javax.swing.JTextArea cuerpoMensaje;
    private javax.swing.JTextField destinatario;
    private javax.swing.JButton enviarMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton noTls;
    private javax.swing.JSpinner puerto;
    private javax.swing.JTextField remitente;
    private javax.swing.JTextField servidorSmtp;
    private javax.swing.JRadioButton siTls;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
